stages:
 - stage: BuildStage
   displayName: Build
   jobs:
   - job: BuildJob

     steps:
     - task: MSBuild@1
       displayName: 'Build solution **/*.sln'

     - task: CopyFiles@2
       displayName: Copy binaries Files
       inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
         **\Output\client\Metroplex*.dll
         **\Output\common\Metroplex*.dll
         **\Output\server\Metroplex*.dll
         **\Libraries\*.dll
        TargetFolder: '$(Build.ArtifactStagingDirectory)\$(Build.DefinitionName)\binaries'
        OverWrite: true
