trigger:
    -None
  branches:
    include:
      - main   # Trigger on pushes to the main branch

stages:
- stage: BuildStage
  displayName: Build
  jobs:
  - job: BuildJob
  
   steps:
    - task: CopyFiles@2   # Example for a Node.js application
      inputs:
      
      SourceFloder: 
         Location: \\10.50.10.4\
         TargetFolder:
         Location: \\10.50.10.4\Code\ 
        OverWrite: true
